### ISSUE TITLE
Can anyone help me, how to add more than one fold change value manually for making chord plot, where two layer of fold change for each gene can be seen.

### ISSUE THREAD

**Issue by bioinformatic-guy** [wencke/wencke.github.io#19]
The highlighted region mentioned how to add it, but I don't understand. Can anyone help me in this regard?

Thanks 

![image](https://github.com/wencke/wencke.github.io/assets/84230574/c5e3f59f-a9aa-4b79-aea6-7e71c1534bf6)

**Comment by Nhien198** [comment]
Thank you very much for your email!I am not online now, I will reply you as soon as possible.Best wish,

**Comment by bioinformatic-guy** [comment]
### **Issue solved**
I think somehow I found a solution to this issue. After making a chord object for function GOChord, we have to export that chord data frame and add one more column as FC manually. then we can import that into GOChord for making the plot. It worked for me.
Thanks
